# ———————————————————————
# Where Upptime stores history + site
# ———————————————————————
owner: joshuasparkes      # GitHub username / org
repo: upptime             # Repository name

# ———————————————————————
# Endpoints to monitor
# ———————————————————————
sites:
  # 1 ▸ Places autocomplete
  - name: Places
    url: "https://content-api.sandbox.junction.dev/places?filter%5Btype%5D%5Beq%5D=city&filter%5Bname%5D%5Blike%5D=par"
    method: GET
    headers:
      - "Accept: application/json"
      - "x-api-key: ${{ secrets.JUNCTION_API_KEY }}"
    expectedStatusCodes: [200]
    maxResponseTime: 8000      # ms
    period: 10                 # minutes between checks

  # 2 ▸ Train Search (one-way)
  - name: Train Search
    url: "https://content-api.sandbox.junction.dev/train-searches"
    method: POST
    headers:
      - "Content-Type: application/json"
      - "x-api-key: ${{ secrets.JUNCTION_API_KEY }}"
    json: |
      {
        "originId": "place_01j804c5h1ew3ask9eh2znw3pz",
        "destinationId": "place_01j804922hfcws9mffxbj8tsv3",
        "departureAfter": "2025-06-24T12:30:00.000Z",
        "returnDepartureAfter": null,
        "passengerAges": [
          { "dateOfBirth": "1995-02-01" }
        ]
      }
    expectedStatusCodes: [201, 200]  # API often returns 201 Created
    maxResponseTime: 10000
    period: 15

# ———————————————————————
# Status-website appearance
# ———————————————————————
status-website:
  cname: demo.upptime.js.org          # change/remove if you don’t use this domain
  # baseUrl: /upptime                 # uncomment if you remove CNAME
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Junction**"
  introMessage: |
    This public status page is powered entirely by GitHub Actions, Issues, and Pages.
    No servers required — just GitHub.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
